# Generated by Django 5.0 on 2025-06-06 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=150)),
                ('code', models.ImageField(upload_to='images/')),
                ('code_description', models.TextField()),
                ('reference', models.TextField()),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoTutorial.objectives')),
            ],
        ),
    ]
