# Generated by Django 5.0 on 2025-06-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoTutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructions',
            options={'verbose_name': 'Instructions', 'verbose_name_plural': 'Instructions'},
        ),
        migrations.AlterModelOptions(
            name='objectives',
            options={'verbose_name': 'Objectives', 'verbose_name_plural': 'Objectives'},
        ),
    ]
