# Generated by Django 5.0 on 2025-06-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoTutorial', '0002_alter_instructions_options_alter_objectives_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectives',
            name='intro',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='step',
            field=models.IntegerField(),
        ),
    ]
